### PR TITLE
updated dropwizard version to 0.8.0-rc2

### PR DESCRIPTION
**Pull request by mrserverless**
This plugin is very useful for building within PaaS containers such as Heroku or Deis. We are currently using version 0.8.0 of Dropwizard and would like to submit this PR to upgrade the version.

### CODE REVIEW

**Comment by tkrille** [comment]
Hello @yunspace and thanks for the PR. Your help is really appreciated but I don't really get the point. Why is it necessary to change the version of the Dropwizard dependency of this plugin in order to support Dropwizard `0.8.0-rc2` in your project? You can always tweak your POM to get the right version afterall. In fact, that's not even necessary. I did a quick test with the following stuff in my POM:

``` xml
[...]
    <dependencies>
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>0.8.0-rc2</version>
        </dependency>
        <dependency>
            <groupId>de.thomaskrille.dropwizard</groupId>
            <artifactId>dropwizard-environment-configuration</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>
[...]
```

This will use the right Dropwizard version `0.8.0-rc2` for the whole project, regardless of what my plugin depends on. Maybe you can tell more about the issues you are facing while using my plugin in a project that uses Dropwizard `0.8.0-rc2`.

**Comment by mrserverless** [comment]
Thanks @tkrille for the prompt reply. We've ran into issues in the past when pulling in transitive dependencies such as conflicting Jersey versions (symptoms described in https://github.com/dropwizard/dropwizard/issues/828) or conflicting Guava versions (ie Governator's v14 vs DW's v18). These errors are not detected at compile time and can be quite confusing when they pop up. Thus we got into a habit of trying to enforcing [dependency convergence](http://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html)

When using your plugin, there weren't any breaking issues actually. The one thing I noticed was that you are dependent on commons-lang 2.6 following DW 0.7.1:

```
org.apache.commons.lang.StringUtils
```

Where as DW 0.8.0-rc2 uses commons-lang3 3.3.2:

```
org.apache.commons.lang3.StringUtils
```

I wrote a quick test for both cases and they both work side by side without any clashes. So I guess we could indeed just use version 1.0. It's just minor house keeping issues such as having 2 versions of commons-lang downloaded into the classpath, and (I haven't tried this yet) not being able to compile when `maven-enforcer-plugin` is used.

**Comment by tkrille** [comment]
thanks for clarification. I remember having such issues myself in the past. Principally, this plugin should be kinda independent of the actual Dropwizard version used. So afaic, bumping the version like you propose might not be a good idea. It will definitely solve your issue but creates issues for other people still using `0.7.1` or a future version.

Thinking this through, I noticed, that you can easily exclude all the transitive dependencies coming from my plugin by declaring the dependency like this in your POM:

``` xml
        <dependency>
            <groupId>de.thomaskrille.dropwizard</groupId>
            <artifactId>dropwizard-environment-configuration</artifactId>
            <version>1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.dropwizard</groupId>
                    <artifactId>dropwizard-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

But I really see the disadvantages in using this approach. Luckily Maven offers a solution for stuff like that: `provided` scope. I tried this out in #2. Would be nice if you can review the solution there. If it satisfies your needs, I would rather go with the `provided` scope instead of bumping the dependency every time Dropwizard makes a new release.

**Comment by mrserverless** [comment]
Closing this in favor of #2

**Pull request closed without merging**
