### PR TITLE
set Dropwizard dependency to scope provided

### PR DESCRIPTION
**Pull request by tkrille**
this should improve compatibility with multiple Dropwizard versions. see
also #1.

### CODE REVIEW

**Comment by tkrille** [comment]
@yunspace: could you please review this solution?

**Comment by mrserverless** [comment]
@tkrille I think this is a good idea, as long as there are no conflicts.

However by adding the `provided` means anyone without `commons-lang` 2.6 in their class path will break when using your `LevenshteinComparator`. Since `org.apache.commons.lang.StringUtils` doesn't exist in 3.3. 

You may need to explicitly declare the `commons-lang` dependency. So that the correct version of commons-lang that you require will be pulled down, regardless of DW 0.7.1 or 0.8.0.

**Comment by tkrille** [comment]
@yunspace Thanks for the hint about `StringUtils`. Actually, it's not my `LevenshteinComparator`. In fact, I just copied the whole configuration mechanism from Dropwizard source and augmented it with the environment variable replacement at the right spot.

So afaic, removing the `StringUtils`, `Levenshtein` and suggestion stuff would be sufficient too. I don't know if anybody is relying on suggestions for misspelled configuration keys. Do you?

**Comment by tkrille** [comment]
I removed the suggestion stuff. There shouldn't be any problematic dependencies left now.

@yunspace Is this Ok with you?

**Comment by mrserverless** [comment]
Actually the suggestion is kinda useful :) I've relied on it a few times when I mistyped a config item out of a long list of items. 

Instead of removing functionalities from the Dropwizard's `ConfigurationException`, it could be re-used simply by moving the `EnvironmentConfigurationFactory` into `io.dropwizard.configuration` package. 

This way it frees you up from copying and pasting the logic into `EnvironmentConfigurationException`, and less dependencies to worry about. I've reflected this in #1,

**Comment by tkrille** [comment]
Ok, I will leave the suggestion stuff as it is. But moving my class to a foreign package seems to be not a good idea. After all it's my class and therefore should belong to my own namespace, despite the fact that I just copied about 90% of it from Dropwizard's original implementation :)

So I think, at this point I would rather stick to either depend on `commons-lang` 2.x or repackage it with the `maven-shade-plugin`. I really try to not introduce any transitive dependencies, as this plugin should be as unobtrusive as possible, especially freeing you from any worries about dependency hell.

I will update my PR during the next hours. Is there anything you did in #1 that you would like to see here, too? Then please, either update your PR, create another one, or tell me and I will incorporate it here.

BTW: I am currently implementing the successor of this project: https://github.com/tkrille/dropwizard-template-config. It takes the whole idea a step further by allowing you to write a [Freemarker](http://freemarker.org) template to replace environment variables and system properties (also anywhere inline a value) and do other cool stuff that Freemarker supports. Would be nice to get some feedback, like ideas for more features, stuff that's wrong, etc., from a real user :) Also if you ever switch to the new thing, please let me know.

**Comment by tkrille** [comment]
Ok, I'm done. I've added the dependency to commons-lang 2.6 and also shaded and repackaged it, so it won't show up in the dependency resolution and should not conflict with any commons-lang dependency of one's project.

@yunspace could you please test this? if it's ok, I will do some cleanup and then make a fresh release out of this.

**Comment by mrserverless** [comment]
sure thing. A bit busy these couple of days. Will test this out and also have a look at your other project.

**Comment by mrserverless** [comment]
@tkrille I've tested this. Please release

**Comment by tkrille** [comment]
thank you

**Comment by tkrille** [comment]
@yunspace version 1.1 has been released and should be available on the central by now.

**Pull request merged**
